name: Build & Test

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Recover cached Pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
        
      - name: Prepare Qt libraries
        run: |
          export QT_DEBUG_PLUGINS=1
          sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 x11-utils 
          sudo apt-get install -y libx11-xcb1 libxcb-image0 libxcb-render-util0 
          sudo apt-get install -y libxcb-keysyms1 libxcb-icccm4 
          sudo apt-get install -y libxcb-randr0 libxcb-xinerama0 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m nltk.downloader stopwords

      - name: Install JABA package
        run: |
          pip install -e .

      - name: Test with pytest
        run: |
          cd JABA
          python -m pytest ../tests --cov=. --cov-report=xml -s

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./JABA/coverage.xml 

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}